#Dan Blankenberg

VCF_NO_VALUE = '.'
VCF_UNPHASED_SEPARATOR = '/'
VCF_PHASED_SEPARATOR = '|'
VCF_GT_PHASED_SEPARATOR = { False: VCF_UNPHASED_SEPARATOR, True: VCF_PHASED_SEPARATOR } 
VCF_INFO_FIELD_SEPARATOR = ";"
VCF_FORMAT_FIELD_SEPARATOR = ":"
